import './globals.css';

import type { Metadata } from 'next';
import { ReactNode } from 'react';

import ThemeProviderWrapper from '@/shared/context/ThemeWrapper';

import { geistMono, geistSans, inter } from '../../public/fonts';

export const metadata: Metadata = {
  title: 'Twitter clone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen max-w-[1440px] overflow-y-auto mx-auto ${geistSans.variable} ${geistMono.variable} ${inter.variable}`}
      >
        <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
      </body>
    </html>
  );
}
