import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import { ReactNode } from 'react';

import ThemeProviderWrapper from '@/shared/context/ThemeWrapper';
import { Footer } from '@/widgets/Footer/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Twitter clone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body className={`h-screen ${geistSans.variable} ${geistMono.variable} ${inter.variable}`}>
        <ThemeProviderWrapper>
          {children}
          <Footer />
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
